### ISSUE TITLE
Questie not showing completed quest turn in locations started this version

### ISSUE THREAD

**Issue by journeym** [trav346/Questie-Epoch#1156]
Questie not showing completed quest turn in locations started this version, all options are enabled, tried relogin, trigger on/off, etc
<img width="1856" height="939" alt="Image" src="https://github.com/user-attachments/assets/f45d295b-a077-4c5c-979c-0c716762bc0d" />

**Comment by RadiantRainbow** [comment]
Same here

**Comment by grimslice** [comment]
[https://gyazo.com/6cc5286d96828c16f8133e9c434d3361](url)

also not tracking progression during the quests.

**Comment by trav346** [comment]
This should be resolved in v1.2.0 due out probably tomorrow. If you're brave you can update to the code on the master branch which should resolve a lot of issues for you guys.

**Comment by journeym** [comment]
<img width="526" height="552" alt="Image" src="https://github.com/user-attachments/assets/7b66ebb0-9bca-4476-a673-78afa17f1987" />
updated, nothing changed

**Comment by journeym** [comment]
btw i always use master branch, not using releases at all

**Comment by journeym** [comment]
Well, only way to get it working was to downgrade to release version 1.1.4.
All other methods failed, tried removing wtf questie files, updated to latest commit, still not working.
So this is from 1.1.4 (notice ? marks = working)
<img width="1752" height="720" alt="Image" src="https://github.com/user-attachments/assets/a029e2a8-4512-4e6e-a0e0-991605bf4a67" />

**Comment by journeym** [comment]
All right, so for everyone that had the same problem, the fix was to check this box (was disabled by default)
<img width="648" height="641" alt="Image" src="https://github.com/user-attachments/assets/65dc53db-5ddc-4c9d-aaf5-30ac0883d7fe" />
